### ISSUE TITLE
Wonky Shapes

### ISSUE THREAD

**Issue by tatarize** [johnbentcope/vpype-ttf#1]
So the reason the shapes are wonky is that they are either all lines or quadratic bezier curves.

https://github.com/opentypejs/opentype.js/blob/c37fcdfbd89c1bd0aac1cecb2b287dfb7d00cee0/src/tables/glyf.js#L214

Here's MIT code that does that correctly. I ran into a font that would have like 3 OFF_CURVE points in a row and it rendered completely mangled. I checked [OpenType.js.org ](https://opentype.js.org/) and the had a glyph checker and it had different numbers of control points and resulting points. I hunted down the code from there.

It's a little weird but it fixes all the wonky text.

![image](https://user-images.githubusercontent.com/3302478/210972142-5965696e-e36f-424c-b9e7-c28dafd368a6.png)

Less wonky inner-p contour.

**Comment by johnbentcope** [comment]
Closed in https://github.com/johnbentcope/vpype-ttf/pull/2
